import type { ShopProduct } from './types';

export const SHOP_PRODUCTS: ShopProduct[] = [
  {
    id: 'classic-tee',
    name: 'Classic Cotton Tee',
    price: 32,
    category: 'Tops',
    sizes: ['S', 'M', 'L', 'XL'],
    color: 'White',
    brand: 'Brand A',
    imageUrl:
      'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=600&q=80',
    newness: 5,
  },
  {
    id: 'linen-shirt',
    name: 'Relaxed Linen Shirt',
    price: 68,
    category: 'Tops',
    sizes: ['S', 'M', 'L'],
    color: 'Blue',
    brand: 'Brand B',
    imageUrl:
      'https://images.unsplash.com/photo-1596755094514-f87e34085b87?auto=format&fit=crop&w=600&q=80',
    newness: 12,
  },
  {
    id: 'rib-knit-top',
    name: 'Rib Knit Long Sleeve',
    price: 45,
    category: 'Tops',
    sizes: ['XS', 'S', 'M', 'L'],
    color: 'Gray',
    brand: 'Brand A',
    imageUrl:
      'https://images.unsplash.com/photo-1434389677669-e08b4cac3105?auto=format&fit=crop&w=600&q=80',
    newness: 8,
  },
  {
    id: 'cargo-pants',
    name: 'Relaxed Cargo Pants',
    price: 56,
    category: 'Bottoms',
    sizes: ['M', 'L', 'XL'],
    color: 'Black',
    brand: 'Brand C',
    imageUrl:
      'https://images.unsplash.com/photo-1473966968600-fa801b869a1a?auto=format&fit=crop&w=600&q=80',
    newness: 3,
  },
  {
    id: 'wide-leg-denim',
    name: 'Wide Leg Denim',
    price: 92,
    category: 'Bottoms',
    sizes: ['S', 'M', 'L', 'XL'],
    color: 'Blue',
    brand: 'Brand B',
    imageUrl:
      'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?auto=format&fit=crop&w=600&q=80',
    newness: 10,
  },
  {
    id: 'pleated-trousers',
    name: 'Pleated Wool Trousers',
    price: 118,
    category: 'Bottoms',
    sizes: ['M', 'L', 'XL'],
    color: 'Gray',
    brand: 'Brand D',
    imageUrl:
      'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?auto=format&fit=crop&w=600&q=80',
    newness: 7,
  },
  {
    id: 'midi-dress',
    name: 'Midi Slip Dress',
    price: 84,
    category: 'Dresses',
    sizes: ['XS', 'S', 'M'],
    color: 'Black',
    brand: 'Brand A',
    imageUrl:
      'https://images.unsplash.com/photo-1595777457583-95e059d581b8?auto=format&fit=crop&w=600&q=80',
    newness: 11,
  },
  {
    id: 'shirt-dress',
    name: 'Belted Shirt Dress',
    price: 72,
    category: 'Dresses',
    sizes: ['S', 'M', 'L', 'XL'],
    color: 'White',
    brand: 'Brand C',
    imageUrl:
      'https://images.unsplash.com/photo-1572804013309-17a7b7b79217?auto=format&fit=crop&w=600&q=80',
    newness: 6,
  },
  {
    id: 'denim-jacket',
    name: 'Oversized Denim Jacket',
    price: 84,
    category: 'Outerwear',
    sizes: ['S', 'M', 'L'],
    color: 'Blue',
    brand: 'Brand B',
    imageUrl:
      'https://images.unsplash.com/photo-1551028719-00167b16eac5?auto=format&fit=crop&w=600&q=80',
    newness: 4,
  },
  {
    id: 'wool-coat',
    name: 'Double Breasted Wool Coat',
    price: 220,
    category: 'Outerwear',
    sizes: ['S', 'M', 'L', 'XL'],
    color: 'Gray',
    brand: 'Brand D',
    imageUrl:
      'https://images.unsplash.com/photo-1539533018447-63fcce2678e3?auto=format&fit=crop&w=600&q=80',
    newness: 14,
  },
  {
    id: 'puffer',
    name: 'Lightweight Puffer',
    price: 140,
    category: 'Outerwear',
    sizes: ['S', 'M', 'L'],
    color: 'Black',
    brand: 'Brand A',
    imageUrl:
      'https://images.unsplash.com/photo-1544022613-e87ca75a784a?auto=format&fit=crop&w=600&q=80',
    newness: 9,
  },
  {
    id: 'leather-sneakers',
    name: 'Leather Sneakers',
    price: 125,
    category: 'Shoes',
    sizes: ['M', 'L', 'XL'],
    color: 'White',
    brand: 'Brand C',
    imageUrl:
      'https://images.unsplash.com/photo-1549298916-b41d501d3772?auto=format&fit=crop&w=600&q=80',
    newness: 13,
  },
  {
    id: 'chelsea-boots',
    name: 'Chelsea Boots',
    price: 165,
    category: 'Shoes',
    sizes: ['M', 'L', 'XL'],
    color: 'Black',
    brand: 'Brand D',
    imageUrl:
      'https://images.unsplash.com/photo-1608256246200-53e635b5b65f?auto=format&fit=crop&w=600&q=80',
    newness: 15,
  },
  {
    id: 'canvas-sneakers',
    name: 'Canvas Low Tops',
    price: 48,
    category: 'Shoes',
    sizes: ['S', 'M', 'L'],
    color: 'Red',
    brand: 'Brand B',
    imageUrl:
      'https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?auto=format&fit=crop&w=600&q=80',
    newness: 2,
  },
  {
    id: 'wrap-dress',
    name: 'Floral Wrap Dress',
    price: 96,
    category: 'Dresses',
    sizes: ['XS', 'S', 'M', 'L'],
    color: 'Red',
    brand: 'Brand B',
    imageUrl:
      'https://images.unsplash.com/photo-1496747611176-843222e1e57c?auto=format&fit=crop&w=600&q=80',
    newness: 16,
  },
  {
    id: 'hoodie',
    name: 'Fleece Hoodie',
    price: 58,
    category: 'Tops',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    color: 'Black',
    brand: 'Brand C',
    imageUrl:
      'https://images.unsplash.com/photo-1556821840-3a63f95609a7?auto=format&fit=crop&w=600&q=80',
    newness: 1,
  },
];
